---
- hosts: ceph_servers
  become: true
  roles:
    - sysctltune
    - addsudowpassw
    - dockerinstall
    - installntpntpdate
    - installcephadm
    - copycephkey
    - pushcephkey
- hosts: ceph_key_server
  become: true
  roles:
    - copycephkey
- hosts: ceph_servers
  become: true
  roles:
    - pushcephkey
