---
#- hosts: ceph_servers
#  become: true
#  roles:
#    - sysctltune
#    - addsudowpassw
#    - dockerinstall
#    - installntpntpdate
#    - installcephadm
- hosts: ceph_key_server
  become: true
  roles:
    - copycephkeys
- hosts: ceph_servers
  become: true
  roles:
    #- setrootkey
    - pushcephkeys
