- name: Download cephadm install script
  command: curl --silent --remote-name --location https://github.com/ceph/ceph/raw/octopus/src/cephadm/cephadm
- name: Change cephadm executable
  ansible.builtin.file:
    path: cephadm
    mode: '0777'
- name: Installing cephadm
  become: yes
  command: ./cephadm install
