- name: Copy ceph.pub from main ceph
  ansible.builtin.fetch:
    src: /etc/ceph/ceph.pub
    dest: /tmp/ceph.pub
    flat: yes
- name: Copy /etc/ceph/ceph.client.admin.keyring
  ansible.builtin.fetch:
    src: /etc/ceph/ceph.client.admin.keyring
    dest: /tmp/ceph.client.admin.keyring
    flat: yes